[source]
workspace="."
paths=["."]

[formatter]
#preset="default"
#preset="psr-12"
preset="pint"
#preset="tempest"
#preset="hack"
#preset="drupal"

print-width=180
tab-width=2
use-tabs=false
trailing-comma=true
single-quote=true

#combine_opening_tag_and_declare=false

control-brace-style="same-line"
remove-trailing-close-tag=true
following-clause-on-newline=false
end-of-line="lf"
closure-brace-style="same-line"
function-brace-style="same-line"
method-brace-style="same-line"
classlike-brace-style="same-line"
inline-empty-control-braces=true
inline-empty-closure-braces=true
inline-empty-function-braces=true
inline-empty-method-braces=true
inline-empty-constructor-braces=true
inline-empty-classlike-braces=true
inline-empty-anonymous-class-braces=true
method-chain-breaking-style="same-line"
first-method-chain-on-new-line=false
method-chain-semicolon-on-next-line=false
preserve-breaking-member-access-chain=true
preserve-breaking-member-access-chain-first-method-on-same-line=true
preserve-breaking-argument-list=true
inline-single-breaking-value-argument=true
preserve-breaking-array-like=true
preserve-breaking-parameter-list=true
preserve-breaking-attribute-list=true
preserve-breaking-conditional-expression=true
preserve-breaking-condition-expression=true
break-promoted-properties-list=false
parameter-attribute-on-new-line=false
line-before-binary-operator=false
indent-binary-expression-continuation=true
omit-redundant-arithmetic-binary-expression-parentheses=false
omit-redundant-bitwise-binary-expression-parentheses=false
preserve-redundant-logical-binary-expression-parentheses=false
always-break-named-arguments-list=false
always-break-attribute-named-argument-lists=false
align-named-arguments=true
align-parameters=true
array-table-style-alignment=true
align-assignment-like=true
sort-uses=true
sort-class-methods=true
separate-use-types=false
expand-use-groups=true
null-type-hint="Question"
parentheses-around-new-in-member-access=true
parentheses-in-new-expression=true
parentheses-in-exit-and-die=true
parentheses-in-attribute=false
space-before-arrow-function-parameter-list-parenthesis=false
space-before-closure-parameter-list-parenthesis=false
space-before-hook-parameter-list-parenthesis=false
inline-abstract-property-hooks=true
space-before-closure-use-clause-parenthesis=false
space-after-cast-unary-prefix-operators=false
space-after-reference-unary-prefix-operator=false
space-after-error-control-unary-prefix-operator=false
space-after-logical-not-unary-prefix-operator=false
space-after-bitwise-not-unary-prefix-operator=false
space-after-increment-unary-prefix-operator=false
space-after-decrement-unary-prefix-operator=false
space-after-additive-unary-prefix-operator=false
space-around-concatenation-binary-operator=false
space-around-assignment-in-declare=true
space-within-grouping-parenthesis=false
empty-line-after-control-structure=false
opening-tag-on-own-line=true
empty-line-after-opening-tag=false
empty-line-after-declare=false
empty-line-after-namespace=false
empty-line-after-use=true
empty-line-after-symbols=false
empty-line-between-same-symbols=false
empty-line-after-class-like-constant=false
empty-line-after-class-like-open=false
empty-line-before-class-like-close=false
empty-line-after-enum-case=false
empty-line-after-trait-use=false
empty-line-after-property=false
empty-line-after-method=false
empty-line-before-return=false
empty-line-before-dangling-comments=false
separate-class-like-members=false
attributes-order="alpha-ascending"
separate-attributes=false
separate-trait-use=true
indent-heredoc=false
uppercase-literal-keyword=true
